plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'io.freefair.lombok' version '6.5.0.3'

}

tasks.register('devJar', Jar) {
    group = 'release'
    from sourceSets.main.output
    description = 'Build a non-reobfuscated development jar'
    archiveClassifier = 'dev'

    exclude 'com/example/examplemod/**'
//
//    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//
//    from {
//        configurations.runtimeClasspath
//                .filter { it.name.contains('asm') }
//                .collect { it.isDirectory() ? it : zipTree(it) }
//    }

    manifest {

        attributes([
                "Specification-Title"     : project.name,
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.version
        ])
    }
}

tasks.register('buildVanillaReobf', Exec) {
    group = 'release'
    description = 'Remap dev jar to vanilla obfuscated jar using SpecialSource'

    dependsOn tasks.named('devJar')

    def specialSourceJar = file("${rootDir}/tools/SpecialSource-1.11.6-shaded.jar")
    def mappingFile = file("${rootDir}/tools/client.txt")

    def devJarTask = tasks.named('devJar', Jar)

    commandLine 'java',
            '-jar', specialSourceJar.absolutePath,
            '-i', devJarTask.get().archiveFile.get().asFile.absolutePath,
            '-o', file("${buildDir}/libs/${base.archivesName.get()}-${project.version}-vanilla-obf.jar").absolutePath,
            '-m', mappingFile.absolutePath,
            '-r',
            '--kill-lvt'
}
tasks.register('buildFabricReobf', Exec) {
    group = 'release'
    description = 'Remap vanilla obfuscated jar to Fabric intermediary jar using TinyRemapper'

    dependsOn tasks.named('buildVanillaReobf')
    def tinyRemapperJar = file("${rootDir}/tools/tiny-remapper-0.13.1-fat.jar")
    def fabricMappingFile = file("${rootDir}/tools/mappings.tiny")
    def minecraftClientJar = file("${rootDir}/tools/1.20.1-vanilla.jar")
    def inputJar = file("${buildDir}/libs/${base.archivesName.get()}-${project.version}-vanilla-obf.jar")
    def outputJar = file("${buildDir}/libs/${base.archivesName.get()}-${project.version}-fabric-intermediary.jar")

    inputs.file inputJar
    inputs.file fabricMappingFile
    inputs.file minecraftClientJar
    outputs.file outputJar

    doFirst {
        outputJar.parentFile.mkdirs()

        commandLine 'java',
                '-jar', tinyRemapperJar.absolutePath,
                inputJar.absolutePath,
                outputJar.absolutePath,
                fabricMappingFile.absolutePath,
                'official',
                'intermediary',
                minecraftClientJar.absolutePath
    }
}


tasks.register('buildCompileJars') {
    group = 'release'
    description = 'Build dev, forge, vanilla and fabric jars into compile directory'

    dependsOn tasks.named('buildFabricReobf')

    if (tasks.findByName('reobfJar') != null) {
        dependsOn tasks.named('reobfJar')
    } else {
        dependsOn tasks.named('jar')
    }

    doLast {
        def compileDir = file("${rootDir}/compile")

//        delete compileDir
//        compileDir.mkdirs()
        compileDir.mkdirs()

        def archiveName = base.archivesName.get()
        def ver = project.version

        def devOut = file("${compileDir}/${archiveName}-${ver}-dev.jar")
        def forgeOut = file("${compileDir}/${archiveName}-${ver}-forge.jar")
        def vanillaOut = file("${compileDir}/${archiveName}-${ver}-vanilla.jar")
        def fabricOut = file("${compileDir}/${archiveName}-${ver}-fabric.jar")
        delete devOut
        delete forgeOut
        delete vanillaOut
        delete fabricOut


        def devJarTask = tasks.named('devJar', Jar).get()
        def normalJarTask = tasks.named('jar', Jar).get()

        def devJarFile = devJarTask.archiveFile.get().asFile

        def forgeJarFile = normalJarTask.archiveFile.get().asFile

        def vanillaJarFile = file("${buildDir}/libs/${archiveName}-${ver}-vanilla-obf.jar")
        def fabricJarFile = file("${buildDir}/libs/${archiveName}-${ver}-fabric-intermediary.jar")


        copy {
            from devJarFile
            into compileDir
            rename { "${archiveName}-${ver}-dev.jar" }
        }

        copy {
            from forgeJarFile
            into compileDir
            rename { "${archiveName}-${ver}-forge.jar" }
        }

        copy {
            from vanillaJarFile
            into compileDir
            rename { "${archiveName}-${ver}-vanilla.jar" }
        }

        copy {
            from fabricJarFile
            into compileDir
            rename { "${archiveName}-${ver}-fabric.jar" }
        }


        //=============
        def packerJar = file("${rootDir}/tools/J2DPacker.jar")

        def devPackOut = file("${compileDir}/noobf.pack")
        def forgePackOut = file("${compileDir}/forge.pack")
        def vanillaPackOut = file("${compileDir}/vanilla.pack")
        def fabricPackOut = file("${compileDir}/fabric.pack")

        delete devPackOut
        delete forgePackOut
        delete vanillaPackOut
        delete fabricPackOut

        def packJar = { File inputJar, File outputPack ->
            exec {
                executable = "java"
                args = [
                        "-jar",
                        packerJar.absolutePath,
                        inputJar.absolutePath,
                        outputPack.absolutePath
                ]
            }
        }

        packJar(devOut, devPackOut)
        packJar(forgeOut, forgePackOut)
        packJar(vanillaOut, vanillaPackOut)
        packJar(fabricOut, fabricPackOut)

        println "==================================="
        println "Generated compile jars:"
        println " - ${file("${compileDir}/${archiveName}-${ver}-dev.jar")}"
        println " - ${file("${compileDir}/${archiveName}-${ver}-forge.jar")}"
        println " - ${file("${compileDir}/${archiveName}-${ver}-vanilla.jar")}"
        println " - ${file("${compileDir}/${archiveName}-${ver}-fabric.jar")}"
        println "==================================="
    }
}


tasks.register('vanillaAndPack', Exec) {
    group = 'release'
    description = '打包为classes.h'

    dependsOn tasks.named('buildVanillaReobf')
    def packerJar = file("${rootDir}/tools/Packer.jar")

    doFirst {
        def vanillaJar = file("${buildDir}/libs/${base.archivesName.get()}-${project.version}-vanilla-obf.jar")

        commandLine 'java',
                '-jar', packerJar.absolutePath,
                vanillaJar.absolutePath
    }
}
version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

// Mojang ships Java 17 to end users in 1.18+, so your mod should target Java 17.
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    // The mappings can be changed at any time and must be in the following format.
    // Channel:   Version:
    // official   MCVersion             Official field/method names from Mojang mapping files
    // parchment  YYYY.MM.DD-MCVersion  Open community-sourced parameter names and javadocs layered on top of official
    //
    // You must be aware of the Mojang license when using the 'official' or 'parchment' mappings.
    // See more information here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md
    //
    // Parchment is an unofficial project maintained by ParchmentMC, separate from MinecraftForge
    // Additional setup is needed to use their mappings: https://parchmentmc.org/docs/getting-started
    //
    // Use non-default mappings at your own risk. They may not always work.
    // Simply re-run your setup task after changing the mappings to update your workspace.
    mappings channel: mapping_channel, version: mapping_version

    // When true, this property will have all Eclipse/IntelliJ IDEA run configurations run the "prepareX" task for the given run configuration before launching the game.
    // In most cases, it is not necessary to enable.
    // enableEclipsePrepareRuns = true
    // enableIdeaPrepareRuns = true

    // This property allows configuring Gradle's ProcessResources task(s) to run on IDE output locations before launching the game.
    // It is REQUIRED to be set to true for this template to function.
    // See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
    copyIdeResources = true

    // When true, this property will add the folder name of all declared run configurations to generated IDE run configurations.
    // The folder name can be set on a run configuration using the "folderName" property.
    // By default, the folder name of a run configuration is the name of the Gradle project containing it.
    // generateRunFolders = true

    // This property enables access transformers for use in development.
    // They will be applied to the Minecraft artifact.
    // The access transformer file can be anywhere in the project.
    // However, it must be at "META-INF/accesstransformer.cfg" in the final mod jar to be loaded by Forge.
    // This default location is a best practice to automatically put the file in the right place in the final jar.
    // See https://docs.minecraftforge.net/en/latest/advanced/accesstransformers/ for more information.
    // accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        // applies to all the run configs below
        configureEach {
            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            property 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            // example of overriding the workingDirectory set in configureEach above
            workingDirectory project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    // Put repositories for dependencies here
    // ForgeGradle automatically adds the Forge maven and Maven Central for you

    // If you have mod jar dependencies in ./libs, you can declare them as a repository like so.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:flat_dir_resolver
    // flatDir {
    //     dir 'libs'
    // }
}

dependencies {
    // Specify the version of Minecraft to use.
    // Any artifact can be supplied so long as it has a "userdev" classifier artifact and is a compatible patcher artifact.
    // The "userdev" classifier will be requested and setup by ForgeGradle.
    // If the group id is "net.minecraft" and the artifact id is one of ["client", "server", "joined"],
    // then special handling is done to allow a setup of a vanilla dependency without the use of an external repository.
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
//    implementation("io.github.humbleui:skija-macos-arm64:0.116.3")
//    implementation("io.github.humbleui:skija-windows-x64:0.116.4")
//    implementation("io.github.humbleui:skija-shared:0.116.4")
//    implementation(fileTree("libs") { include("*.jar") })

    compileOnly 'org.projectlombok:lombok:1.18.34'
    implementation 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
    testImplementation 'org.projectlombok:lombok:1.18.34'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'

    // Example mod dependency with JEI - using fg.deobf() ensures the dependency is remapped to your development mappings
    // The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
    // compileOnly fg.deobf("mezz.jei:jei-${mc_version}-common-api:${jei_version}")
    // compileOnly fg.deobf("mezz.jei:jei-${mc_version}-forge-api:${jei_version}")
    // runtimeOnly fg.deobf("mezz.jei:jei-${mc_version}-forge:${jei_version}")

    // Example mod dependency using a mod jar from ./libs with a flat dir repository
    // This maps to ./libs/coolmod-${mc_version}-${coolmod_version}.jar
    // The group id is ignored when searching -- in this case, it is "blank"
    // implementation fg.deobf("blank:coolmod-${mc_version}:${coolmod_version}")

    // For more info:
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}


// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {

//    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//
//    from {
//        configurations.runtimeClasspath
//                .filter { it.name.contains('asm') }
//                .collect { it.isDirectory() ? it : zipTree(it) }
//    }

    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    // This is the preferred method to reobfuscate your jar file
    finalizedBy 'reobfJar'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}
// However if you are in a multi-project build, dev time needs unobfed jar files, so you can delay the obfuscation until publishing by doing:
// tasks.named('publish').configure {
//     dependsOn 'reobfJar'
// }

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
